<!--
 * @Author              : qxp
 * @Date                : 2021-03-25 10:41:53
 * @LastEditors         : Please set LastEditors
 * @LastEditTime        : 2021-03-25 10:54:04
 * @FilePath            : \new\6 Es6\10 Promise 对象\5 Promise.all().html
-->
Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
const p = Promise.all([p1, p2, p3]);
上面代码中，Promise.all()方法接受一个数组作为参数，p1、p2、p3都是 Promise 实例，
如果不是，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise
实例，再进一步处理。另外，Promise.all()方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。

<script>
    const databasePromise = connectDatabase();

    const booksPromise = databasePromise
        .then(findAllBooks);

    const userPromise = databasePromise
        .then(getCurrentUser);

    Promise.all([
        booksPromise,
        userPromise
    ]).then(([books, user]) => pickTopRecommendations(books, user));
    // 上面代码中，booksPromise和userPromise是两个异步操作，只有等到它们的结果都返回了，才会触发pickTopRecommendations这个回调函数。
</script>

注意，如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
<script>
    const p1 = new Promise((resolve, reject) => {
        resolve('hello');
    })
        .then(result => result)
        .catch(e => e);

    const p2 = new Promise((resolve, reject) => {
        throw new Error('报错了');
    })
        .then(result => result)
        .catch(e => e);

    Promise
        .all([p1, p2])
        .then(result => console.log(result))
        .catch(e => console.log(e));
    // ["hello", Error: 报错了]
    // 上面代码中，p1会resolved，p2首先会rejected，但是p2有自己的catch方法，该方法返回的是一个新的 Promise 实例，p2指向的实际上是这个实例。该实例执行完catch方法后，也会变成resolved，
    // 导致Promise.all()方法参数里面的两个实例都会resolved，因此会调用then方法指定的回调函数，而不会调用catch方法指定的回调函数。
    // 如果p2没有自己的catch方法，就会调用Promise.all()的catch方法。
</script>

<script>
    const s1 = new Promise((resolve, reject) => {
        resolve('hello');
    })
        .then(result => console.log('s1:', result))
        .catch(e => e);

    const s2 = new Promise((resolve, reject) => {
        throw new Error('报错了');
    })
        .then(result => console.log('s2:', result))
        .catch(e =>  console.log('s2:', e));

    Promise.all([p1, p2])
        .then(result => console.log(result))
        .catch(e => console.log(e));

</script>

